### ISSUE TITLE
Support /summarize_time.cgi or equivalent functionality? 

### ISSUE THREAD

**Issue by AJRepo** [python-bugzilla/python-bugzilla#145]
Nice library!

I tried to use this library to pull the time summary that you can get in bugzilla at /summarize_time.cgi?start_date=.... 

The URL /summarize_time.cgi  generates a report that gives all the worktime for all the bugs passed in by variables id=n1,n2,n3,... between start_date=YYYY-MM-DD and end_date=YYYY-MM-DD. Good for reports and invoices. 

I looked for a summarize feature in the python-bugzilla library but didn't see anything. I tried calling  /summarize_time.cgi from   bzapi.url_to_query() but that end URL wasn't a valid URL endpoint for python-bugzilla. 

I found I could iterate through the bugs with a standard search and generate he same thing and so  created a python program that calls python-bugzilla and generates the same thing by iterating over the returned bugs and adding up the work times. But before going much more with that I thought I'd ask if there was something already in the library that generates that summary time data that I was missing or if I should just continue with the iteration/addition method.

Thanks!

**Comment by crobinso** [comment]
Thanks for the kind words. Because summarize_time.cgi is not a part of bugzilla's REST/XMLRPC API, and more like a webapp shipped with bugzilla that uses the API to achieve a specific goal, it's not suitable for the python-bugzilla API IMO. We really try to limit this project to being a python wrapper for bugzilla's actual API, and the /usr/bin/bugzilla command line tool to interact with the API.

But if you write a script that works, feel free to link it in this issue incase anyone else stumbles here via google, it may be useful for them too.

**Comment by AJRepo** [comment]
Here's the script I wrote:  https://github.com/AJRepo/bugzilla_timereports

I now use it for automated weekly reports by product and for automated invoicing.
