### ISSUE TITLE
Is there a method to close session?

### ISSUE THREAD

**Issue by mattiaverga** [python-bugzilla/python-bugzilla#157]
Recently I've started to see errors like
```
bugzilla.exceptions.BugzillaError: Login failed: The account you are using has too many current logins. The maximum number of concurrent logins is 42 and you have 42. You will need to wait until enough sessions expire before you can login again. Sessions expire after being unused for 7 days. All sessions are removed during an upgrade regardless of age. If you are using the API you might consider using API_KEYs instead of logging in. If you don't want to use API_KEYs then you need to logout to prevent being locked out.
```

I don't see anything in python-bugzilla to close the session after a script is completed, is there?
I got those errors with user+pass authentication, but I've just switched to api key authentication, is that enough to avoid further errors? It would be nice, however, to explicitly close a session, though.

**Comment by crobinso** [comment]
Thanks for the report. I've never seen that error before, I wonder if it's newly added to rhbz, there's a lot of auth changes happening there. I'm not even really sure what it means, that you've called login() 42 separate times so rhbz has returned a total of 42 login tokens to you? I kinda thought there was only one login token at a time, and when login() was called a second time, the first one was invalidated.

Anyways, figuring out what it means and mitigating it is kind of a lost cause at this point, because in the next few weeks rhbz is going to be completely disabling login() and mandating use of API keys, which I'm guessing do not have this problem. So as things stand now this is WONTFIX, but if things change we can reopen
