### ISSUE TITLE
Can we query with Classification name?

### ISSUE THREAD

**Issue by zhangyuting** [python-bugzilla/python-bugzilla#20]
Hi,

When doing a query with build_query, we can specify product name, component name, however I want to query with Classification name(refer to this page: https://partner-bugzilla.redhat.com/query.cgi?format=advanced). Do we support this?

Thanks,
Yuting

**Comment by crobinso** [comment]
Yes it works, but it's a little roundabout:

bzapi = bugzilla.Bugzilla("partner-bugzilla.redhat.com")
query = bzapi.build_query(...)
query["classification"] = XXX
bugs = bzapi.query(query)

Since 'classification' isn't listed as an official query field in the bugzilla XMLRPC docs, it's not available as an explicit build_query() parameter, but that method above appears to work with bugzilla.redhat.com at least.
