### ISSUE TITLE
RFE: read default URL from ~/.config/python-bugzilla/bugzillarc

### ISSUE THREAD

**Issue by albfan** [python-bugzilla/python-bugzilla#27]
This line is far from agnostic:

https://github.com/python-bugzilla/python-bugzilla/blob/master/bin/bugzilla#L38

Seems a cool hack for redhat users, but I find it annoying to write `--bugzilla url` everytime

I bypass it with an alias:

    $ alias gbugzilla=' bugzilla --bugzilla bugzilla.gnome.org'

but would be great to read defaults from a ~/.config/bugzillarc or similar.

That would spread the usage from this fantastic command line tool

**Comment by crobinso** [comment]
Thanks for the suggestion, indeed we should fix this. There's already ~/.config/python-bugzilla/bugzillarc support that allows specifying user= and password= per site URL, we could extend that to handle

[DEFAULT]
url = "my-bugzilla-url"

**Comment by albfan** [comment]
Sounds great. Do you need a PR?

**Comment by crobinso** [comment]
thanks for the offer, that would be appreciated. though there's a few other tricky bits I still need to figure out... right now the bugzillarc parsing is tied to the Bugzilla() class so we might have to break that out so the CLI tool can use it first, either that or alter the API object to consumer the default URL as well.

also I'm cutting a release shortly since we are way overdue, so this will probably be for the following release FYI

**Comment by albfan** [comment]
Cool!

**Comment by alejandro-colomar** [comment]
Could you please add a manual page bugzillarc(5) documenting what is available in that file?
