### ISSUE TITLE
getcomponents() queries every product and times out

### ISSUE THREAD

**Issue by ktdreyer** [python-bugzilla/python-bugzilla#49]
The getcomponents() call no longer works on Red Hat's Bugzilla :

```python
from bugzilla import Bugzilla
bz = Bugzilla('bugzilla.redhat.com')
result = bz.getcomponents('Red Hat Ceph Storage')
print(result)
```
This example just ends up hitting connection reset errors and retrying over and over. Who knows what's happening to the backend systems :)

Even though I'm only asking for the components of a single product, python-bugzilla ends up querying every single product ID first in order to cache the information for all products. This massive `Product.get` call with 350 product IDs just times out.

**Comment by crobinso** [comment]
Thanks for the report. Yeah the code is a bit ridiculous here since we try to support bugzilla 4.0 and earlier where product info could only be queried by ID, so we need to query IDs first then try to map ID to name. But we should just drop all that stuff

**Comment by ktdreyer** [comment]
Thanks @crobinso . Here's what I'm doing in the meantime (I only need the component names).
```python
from bugzilla import Bugzilla
bz = Bugzilla('bugzilla.redhat.com')
result = bz._proxy.Product.get({'names': ['Red Hat Ceph Storage']})
# I only need the component names
names = [c['name'] for c in result['products'][0]['components']]
```

**Comment by crobinso** [comment]
Okay so I dug in a bit more. It needs some explanation.

First off let me say that python-bugzilla is an old API and has lots of historical baggage so some things can't be changed quickly without risk of breaking other users.

The getcomponents() API behind the scenes actually doesn't use Product.get, it uses Bug.legal_values({"product_id": id, 'values': 'components'}. This API only takes a product_id which is an integer. So when a product string name is passed in, we need to do a Product.get call to fetch all product info to map name->id.

legal_values is deprecated upstream so it's unlikely it will ever be expanded to take a product name. API docs say that legal_values should be replaced with Bug.fields however I can't see any way to actually do the equivalent of ask for all component names for a particular product. Boo

This same functionality can be implemented like you do with Product.get, however on bugzilla.redhat.com for Products like Fedora where there are 1000s of components, even a minimal Product.get call asking for only include_fields=[components.name] is 10x slower than legal_values. So changing the backend impl is going to possibly break things for anyone listing Fedora component names or similar

I updated the code to be a bit more efficient with the implicit Product.get call here, only asking for include_fields=["name", "id"] which should make it a bit faster. But in the short term that's the best we can do. Long term I will likely have to implement this with Product.get or hopefully upstream absorbs rhbz's custom Component.get, but I won't be exposing that in python-bugzilla API since we've been bitten by exposing non-upstream APIs

**Comment by crobinso** [comment]
Actually thinking about it some more I missed that we could do a minimal Product.get(names=[name]) to get the id mapping in this case. Might save a few seconds but it's a minor optimization
