### ISSUE TITLE
idea: "checkdupes" kwarg for addcomment()

### ISSUE THREAD

**Issue by ktdreyer** [python-bugzilla/python-bugzilla#53]
I wonder if it would be worthwhile to add a new kwarg to python-bugzilla's `addcomment()` method, like `addcomment(checkdupes=True)` or something. When set to True, python-bugzilla could query the bug for identical comments before adding another one.

This could provide a straightforward way for apps to avoid posting duplicate comments. See https://github.com/fedora-infra/bodhi/issues/1532 for example, and I've written similar workarounds with `getcomments()` + `addcomment()` in some other apps. What do you think?

**Comment by crobinso** [comment]
Thanks for the suggestion. I don't really like the idea of adding this to addcomment(). Maybe this could exist as its own helper like Bug.has_comment(msg) or something but it may not even be worth handling that, I'd need to see what an implementation looks like.

Over time I've realized that adding high level features on top of the API wrapper calls is a pain in the butt. For example, in this case it hides from the user exactly what is going on, like fetching all bug comments which (depending on how you initially queried bugzilla) can mean an extra round trip, which is very slow. This encourages very slow code and increased bugzilla load, especially from automated tools. If users are forced to do the minimal dupe detection themselves, it's easier for them to detect where slowness is coming from, like the added round trip.

Somewhat related, bodhi shouldn't be using addcomment in this case, since it means one bugzilla round trip per bug (and round trips here aren't like quick http round trips, we are talking 1 second minimum for bugzilla.redhat.com XMLRPC). Instead bodhi should be using build_update/update_bugs to do a batch operation. Those APIs are very thin wrappers around the XMLRPC APIs so a checkdupes= option isn't a good fit there either IMO
